spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/customer
    username: sa
    password:
    sqlScriptEncoding: utf-8
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate