spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:/customer
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    sqlScriptEncoding: utf-8
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
security:
  basic:
    enabled: false